# Generated by Django 4.1.13 on 2024-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('types', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
