# Generated by Django 4.1.13 on 2024-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
