# Generated by Django 4.1.13 on 2024-03-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_data',
            field=models.CharField(default='no data', max_length=700),
        ),
    ]
