# Generated by Django 4.1.13 on 2024-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='solved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answers',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
