# Generated by Django 4.1.13 on 2024-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_solved_quiz_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_data',
            field=models.JSONField(default=dict, max_length=700),
        ),
    ]
