# Generated by Django 4.1.13 on 2024-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_quiz_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='solved',
            field=models.DateField(null=True),
        ),
    ]
