# Generated by Django 4.1.13 on 2024-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_mistakes',
            field=models.JSONField(default=dict, max_length=700),
        ),
    ]
