# Generated by Django 3.2.1 on 2024-03-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_user_mistakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='user_answers',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
